### ISSUE TITLE
[ISSUE] Issue with testing for a Solid Start library 

### ISSUE THREAD

**Issue by qlaffont** [solidjs/solid-jest#9]
Hello,
I'm currently working on a Solid Start library. 

I'm currently using [tsdx](https://github.com/jaredpalmer/tsdx) to package my app and jest to test my application.

Currently, I have an error when I execute tests :
```
➜  solid-protected-auth git:(master) pnpm test 

> solidstart-protected-auth@2.0.205 test /home/quentin/Documents/dev/solid-protected-auth
> jest

 PASS  test/currentURLIsAllowed.test.ts
 FAIL  test/solidstart-protected-auth.test.tsx
  ● Test suite failed to run

    SyntaxError: /home/quentin/Documents/dev/solid-protected-auth/node_modules/.pnpm/solid-start@0.3.7_@solidjs+meta@0.28.6_@solidjs+router@0.8.3_solid-js@1.8.3_vite@4.5.0/node_modules/solid-start/index.tsx: Unexpected token, expected "," (12:7)

      10 |   useRoutes,
      11 |   useSearchParams,
    > 12 |   type RouteDataFunc,
         |        ^
      13 |   type RouteDataFuncArgs
      14 | } from "@solidjs/router";
      15 | export type { APIEvent } from "./api";

      12 | } from 'solid-js';
      13 | import { isServer } from 'solid-js/web';
    > 14 | import { Meta, redirect, useLocation } from 'solid-start';
         | ^
      15 |
      16 | import { currentURLIsAllowed } from './currentURLIsAllowed';
      17 |

      at constructor (node_modules/.pnpm/@babel+parser@7.23.0/node_modules/@babel/parser/src/parse-error.ts:81:19)
      at JSXParserMixin.toParseError [as raise] (node_modules/.pnpm/@babel+parser@7.23.0/node_modules/@babel/parser/src/tokenizer/index.ts:1487:19)
      at JSXParserMixin.raise [as unexpected] (node_modules/.pnpm/@babel+parser@7.23.0/node_modules/@babel/parser/src/tokenizer/index.ts:1528:16)
      at JSXParserMixin.unexpected [as expect] (node_modules/.pnpm/@babel+parser@7.23.0/node_modules/@babel/parser/src/parser/util.ts:149:28)
      at JSXParserMixin.expect [as parseExportSpecifiers] (node_modules/.pnpm/@babel+parser@7.23.0/node_modules/@babel/parser/src/parser/statement.ts:2800:14)
      at JSXParserMixin.parseExportSpecifiers [as maybeParseExportNamedSpecifiers] (node_modules/.pnpm/@babel+parser@7.23.0/node_modules/@babel/parser/src/parser/statement.ts:2479:36)
      at JSXParserMixin.maybeParseExportNamedSpecifiers [as parseExport] (node_modules/.pnpm/@babel+parser@7.23.0/node_modules/@babel/parser/src/parser/statement.ts:2371:32)
      at JSXParserMixin.parseExport [as parseStatementContent] (node_modules/.pnpm/@babel+parser@7.23.0/node_modules/@babel/parser/src/parser/statement.ts:597:25)
      at JSXParserMixin.parseStatementContent [as parseStatementLike] (node_modules/.pnpm/@babel+parser@7.23.0/node_modules/@babel/parser/src/parser/statement.ts:417:17)
      at JSXParserMixin.parseStatementLike [as parseModuleItem] (node_modules/.pnpm/@babel+parser@7.23.0/node_modules/@babel/parser/src/parser/statement.ts:354:17)
      at JSXParserMixin.parseModuleItem [as parseBlockOrModuleBlockBody] (node_modules/.pnpm/@babel+parser@7.23.0/node_modules/@babel/parser/src/parser/statement.ts:1394:16)
      at JSXParserMixin.parseBlockOrModuleBlockBody [as parseBlockBody] (node_modules/.pnpm/@babel+parser@7.23.0/node_modules/@babel/parser/src/parser/statement.ts:1368:10)
      at JSXParserMixin.parseBlockBody [as parseProgram] (node_modules/.pnpm/@babel+parser@7.23.0/node_modules/@babel/parser/src/parser/statement.ts:213:10)
      at JSXParserMixin.parseProgram [as parseTopLevel] (node_modules/.pnpm/@babel+parser@7.23.0/node_modules/@babel/parser/src/parser/statement.ts:195:25)
      at JSXParserMixin.parseTopLevel [as parse] (node_modules/.pnpm/@babel+parser@7.23.0/node_modules/@babel/parser/src/parser/index.ts:45:10)
      at parse (node_modules/.pnpm/@babel+parser@7.23.0/node_modules/@babel/parser/src/index.ts:66:38)
      at parser (node_modules/.pnpm/@babel+core@7.23.2/node_modules/@babel/core/src/parser/index.ts:28:19)
          at parser.next (<anonymous>)
      at normalizeFile (node_modules/.pnpm/@babel+core@7.23.2/node_modules/@babel/core/src/transformation/normalize-file.ts:50:24)
          at normalizeFile.next (<anonymous>)
      at run (node_modules/.pnpm/@babel+core@7.23.2/node_modules/@babel/core/src/transformation/index.ts:39:36)
          at run.next (<anonymous>)
      at transform (node_modules/.pnpm/@babel+core@7.23.2/node_modules/@babel/core/src/transform.ts:29:20)
          at transform.next (<anonymous>)
      at evaluateSync (node_modules/.pnpm/gensync@1.0.0-beta.2/node_modules/gensync/index.js:251:28)
      at sync (node_modules/.pnpm/gensync@1.0.0-beta.2/node_modules/gensync/index.js:89:14)
      at fn (node_modules/.pnpm/@babel+core@7.23.2/node_modules/@babel/core/src/errors/rewrite-stack-trace.ts:99:14)
      at transformSync (node_modules/.pnpm/@babel+core@7.23.2/node_modules/@babel/core/src/transform.ts:66:52)
      at ScriptTransformer.transformSource (node_modules/.pnpm/@jest+transform@29.7.0/node_modules/@jest/transform/build/ScriptTransformer.js:545:31)
      at ScriptTransformer._transformAndBuildScript (node_modules/.pnpm/@jest+transform@29.7.0/node_modules/@jest/transform/build/ScriptTransformer.js:674:40)
      at ScriptTransformer.transform (node_modules/.pnpm/@jest+transform@29.7.0/node_modules/@jest/transform/build/ScriptTransformer.js:726:19)
      at Object.require (src/index.tsx:14:1)
      at Object.require (test/solidstart-protected-auth.test.tsx:19:1)

Test Suites: 1 failed, 1 passed, 2 total
Tests:       5 passed, 5 total
Snapshots:   0 total
Time:        8.642 s
Ran all test suites.
 ELIFECYCLE  Test failed. See above for more details.
```

I have tried to get deps and files from solid ts jest template (`npx degit solidjs/templates/ts-jest my-solid-project`), without success. I need help ^^ !

Code repository : https://github.com/qlaffont/solidstart-protected-auth

Thanks !

**Comment by qlaffont** [comment]
:wave: @ryansolid

**Comment by qlaffont** [comment]
:wave:
